### ISSUE TITLE
Add min/max width/height

### ISSUE THREAD

**Issue by ianharrigan** [haxeui/haxeui-core#144]
It would be advantageous to not allow a component to go above / below and specific size. This can be accomplished with a new min/max width and height css style. 

## Expected Behavior
If set a component should not go above or below the specified min / max sizes.

## Current Behavior
No current implementation, therefore no current behaviour.

## Possible Solution
Add new css properties: 

```css
.something {
    min-width: 50px;
    min-height: 50px;
    max-width: 500px;
    max-height: 500px;
}
```

(note: these can / should also be exposes as component properties via build macros, eg `@style(layout) minWidth:Null<Float>` - this means they can also be used in code and via xml)
