### ISSUE TITLE
hidpi UIs

### ISSUE THREAD

**Issue by fullofcaffeine** [haxeui/haxeui-core#180]
Hey Ian!

How would you support hidpi displays? For example, if you design a desktop UI for both retina and 1080p displays, you usually double the amount of pixels for that specific image (and UI controls), so you have two versions of the same image, one with the double amount of pixels and another one that is suited for 1080p and below, and use CSS media queries to select the right one based on the resolution: https://css-tricks.com/snippets/css/retina-display-media-query/.

How would you deal with that currently?

**Comment by ianharrigan** [comment]
Hi Marcelo,

So there are no such things as media queries currently, though its something that certainly makes sense to put in there (will need some time and investigation though, i would also like to add css transitions in too, but again, will take some time / investigation).

As for "non images", ie, controls / text, it depends on which backend - but custom drawn backends _should_ be DPI aware and should auto scale based on the device dpi... assuming that 1) the device dpi has been implemented for the backend and b) the dpi is above the threshold (140 i believe).

Another option is to use "rem" units in the CSS... then things should scale based on font size. Neither are a 100% solution and neither help with selecting an image based on DPI however. 

One option i could think of as a work around for now, would be, in code, to work out which .css file to include before you application starts - again, its not ideal, but it would work until media queries could be implemented in the core.

**Comment by ianharrigan** [comment]
Hi again, just a quick update to let you know that im actively working in this, below is a little demo of it working (with only media queries) - gif is a bit on the large side :)

css used: 
```css
#main {
    padding: 10px;
}

.header {
    background-color: #9933cc;
    color: #ffffff;
    padding: 30px;
}

.header label {
    font-size: 32px;
    color: white;
}

.menu {
    width: 100%;
}

.menu-item {
    background-color: #33b5e5;
    padding: 8px;
    filter: drop-shadow(1, 45, #000000, 0.5, 2, 2, 1, 3, false);
    width: 100%;
}

.menu-item label {
    font-size: 20px;
    color: white;
}

.text {
    width: 100%;
}

.side {
    padding: 20px;
    background-color: #33b5e5;
    filter: drop-shadow(1, 45, #000000, 0.5, 2, 2, 1, 3, false);
    width: 100%;
}

.side label {
    color: white;
}

#logo {
    background-image: "haxeui-core/styles/default/haxeui_tiny.png";
}


#logoButton {
    icon: "haxeui-core/styles/default/haxeui_tiny.png";
}


@media (min-width: 500px) {
    .menu {
        width: 25%;
    }

    .text {
        width: 75%;
    }

    .side {
        width: 100%;
    }
    
    #logoButton {
        icon: "haxeui-core/styles/default/haxeui_small.png";
    }
}

@media (min-width: 750px) {
    .menu {
        width: 25%;
    }

    .text {
        width: 50%;
    }

    .side {
        width: 25%;
    }
    
    
    #logoButton {
        icon: "haxeui-core/styles/default/haxeui.png";
    }
}
```


![demo](https://user-images.githubusercontent.com/3024242/32782257-25dda782-c948-11e7-9584-9d640808fb44.gif)
