### ISSUE TITLE
question: how do I change text color of a label inside optionbox, checkbox

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-core#234]
I know that there is a main.css where I can change css classes, I can change color of usual Labels
but what about labels that are inside other controls like checkbox or optionbox?
Also how do I know the style names in general, just in case I want to style all elements in future?
Thanx!

**Comment by ianharrigan** [comment]
Generally it should propagate. So for example:

```css
.button {
   color: red;
}
```

is in essence the same as doing:

```css
.button .label {
   color: red;
}
```

or 

```css
#myButton {
   color: blue;
}
```

is the same as

```css
#myButton .label {
    color: blue;
}
```

Same applies to inline styles:

```xml
<button text="Button 1" style="color: red" />
<button text="Button 2" style="color: blue" />
```

There (will eventually - i know, usual excuse! :) ) be documentation like this: http://haxeui.org/api/haxe/ui/components/Button.html that shows the sub components, their types and their ids.  But (where possible, color - forecolor - for a button for example, will lead to the fore colour of the label also).

That help any?

Cheers,
Ian

Note: 

```css
.button { 
    border: 5px solid black;
}
```

is _very_ different to:

```css
.button .label {
    border: 5px solid black;
}
```
